/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as demo from "./demo";
export type { demo };
import type * as paymaster from "./paymaster";
export type { paymaster };
